ProjectRepo/Models/ErrorViewModel.cs
using System;

namespace PortfolioApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectRepo/Models/PortfolioDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PortfolioApp.Models
{
    public class PortfolioDetailViewModel
    {
        public string Description { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CompletionDate { get; set; }
        public string PhotoUrl { get; set; }
        public List<string> Tags { get; set; } = new List<string>();
        public string Status { get; set; }
    }
}

ProjectRepo/Models/PortfolioListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PortfolioApp.Models
{
    public class PortfolioListViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CompletionDate { get; set; }
        public string PhotoUrl { get; set; }
        public List<string> Tags { get; set; } = new List<string>();
        public string Status { get; set; }
    }
}

ProjectRepo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PortfolioApp.Models;

namespace PortfolioApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectRepo/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PortfolioApp.Database;
using PortfolioApp.Domain;
using PortfolioApp.Models;


namespace PortfolioApp.Controllers
{
    public class PortfolioController : Controller
    {
        private readonly PortfolioDb _projectDb;

        public PortfolioController(PortfolioDb portfolioDb)
        {
            _projectDb = portfolioDb;
        }

        public async Task<IActionResult> Index()
        {
            List<PortfolioListViewModel> vmList = new List<PortfolioListViewModel>();
            var portfolios = await _projectDb.Portfolio.Include(x => x.Status).Include(x => x.PortfolioTags).ThenInclude(x => x.Tag).ToListAsync();
            foreach (var portfolio in portfolios)
            {
                PortfolioListViewModel vm = new PortfolioListViewModel()
                {
                    Id = portfolio.Id,
                    CompletionDate = portfolio.CompletionDate,
                    Status = portfolio.Status.Description,
                    Tags = portfolio.PortfolioTags.Select(x => x.Tag.Description).ToList(),
                    PhotoUrl = portfolio.PhotoUrl,
                    Title = portfolio.Title
                };
                vmList.Add(vm);
            }
            return View(vmList);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Portfolio portfolio = await _projectDb.Portfolio.Include(x => x.Status).Include(x => x.PortfolioTags).ThenInclude(x => x.Tag).FirstOrDefaultAsync(x => x.Id == id);
            PortfolioDetailViewModel vm = new PortfolioDetailViewModel()
            {
                Title = portfolio.Title,
                CompletionDate = portfolio.CompletionDate,
                Status = portfolio.Status.Description,
                Tags = portfolio.PortfolioTags.Select(x => x.Tag.Description).ToList(),
                PhotoUrl = portfolio.PhotoUrl,
                Description = portfolio.Description
            };
            return View(vm);
        }
    }
}

ProjectRepo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjectRepo/Views/Portfolio/Detail.cshtml
@model PortfolioDetailViewModel;

<strong>Title</strong>
<p>@Model.Title</p>

@if (!String.IsNullOrEmpty(Model.PhotoUrl))
{
    <strong>Photo</strong>
    <img src="@Model.PhotoUrl" />
}

<strong>Description</strong>
<p>@Model.Description</p>


<strong>Completion Date</strong>
<p>@Model.CompletionDate</p>


<strong>Status</strong>
<p>@Model.Status</p>


<strong>Tags</strong>
@foreach (var tag in Model.Tags)
{
    <ul>
        <li>@tag</li>
    </ul>
}

ProjectRepo/Views/Portfolio/Index.cshtml
@model IEnumerable<PortfolioListViewModel>


@using Microsoft.AspNetCore.Identity
@inject SignInManager<PortfolioApp.Domain.PortfolioUser> signInManager



@if (signInManager.IsSignedIn(User))
{
    <a asp-controller="Project" asp-action="Create">Add new project</a>
}

@{
    if (Model.Count() == 0)
    {
        <br />
        <strong>There are currently no projects listed.</strong>
    }

    else
    {
        <table>
            <thead>
                <tr>
                    <th>
                        Project
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Completion Date
                    </th>
                    <th>
                        Tags
                    </th>
                    @if (signInManager.IsSignedIn(User))
                    {
                        <th> Options </th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (PortfolioListViewModel portfolio in Model)
                {
                    <tr>
                        <td class="info">
                            <a asp-controller="Portfolio" asp-action="Detail" asp-route-id="@portfolio.Id">@portfolio.Title</a>
                        </td>

                        <td class="info">
                            @portfolio.Status
                        </td>

                        <td class="info">
                            @portfolio.CompletionDate
                        </td>

                        <td class="info">
                            @{
                                if (portfolio.Tags.Count == 0)
                                {
                                    <p>No tags</p>
                                }

                                else
                                {
                                    foreach (string tag in portfolio.Tags)
                                    {
                                        <p>@tag</p>
                                    }
                                }
                            }
                        </td>
                        @if (signInManager.IsSignedIn(User))
                        {
                            <td class="feature">
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    }
}



<style>
    table, td {
        border-bottom: 1px solid black;
    }

    .info {
        width: 20vw;
    }

    img {
        width: 100px;
    }
</style>

ProjectRepo/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<PortfolioApp.Domain.PortfolioUser> signInManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PortfolioApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PortfolioApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PortfolioApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>